### ISSUE TITLE
Descripción del Problema de relaciones

### ISSUE THREAD

**Issue by GusGA** [manuelramoslg/test-acidlabs#1]
Hola Manuel

¿Podrías describir el problema de las relaciones que comentaste en el correo a través de un issue de github?

Yo estoy haciendo seguimiento de tu proyecto, así podré comentar el código que tengas escrito acá.

Saludos

**Comment by manuelramoslg** [comment]
Almacena correctamente el Artista y sus Albums, almacena los Tracks pero por artista no por Album,  estoy revisando las relaciones y me parecen correctas.

Voy a modificar el controller ya que por la manera en que almacena estoy llamando a los Tracks del Artist y no a los Tracks del Album.

**Comment by manuelramoslg** [comment]
Solucionado el problema de buscar los tracks de album y no del artista.
Solucionado problema de relación de las tablas (estaba usando mal el ActiveRecord).
